# Generated by Django 5.2.1 on 2025-12-02 06:00
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkontestrelation',
            name='disqualified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userkontestrelation',
            name='disqualified_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userkontestrelation',
            name='is_disqualified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='userkontestrelation',
            unique_together={('kontest', 'user')},
        ),
    ]